package com.capstone.gradely.model.enums;

public enum Grade {
	KINDERGARDEN,
	FIRST_GRADE,
	SECOND_GRADE,
	THIRD_GRADE,
	FOURTH_GRADE,
	FIFTH_GRADE,
	SIXTH_GRADE,
	SEVENTH_GRADE,
	EIGTH_GRADE,
	NINTH_GRADE,
	TENTH_GRADE,
	ELEVENTH_GRADE,
	TWELVETH_GRADE
}
