export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';

export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_ALL_COURSES_NEW_ASSIGNMENT = 'GET_ALL_COURSES_NEW_ASSIGNMENT';
export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE COURSE';

export const UPDATE_STUDENT_SCORE = 'UPDATE_STUDENT_SCORE';

export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';

export const GET_COURSE = 'GET_COURSE';

export const UPDATE_USER = 'UPDATE_USER';
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_PHONE = 'ADD_PHONE';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_PHONE = 'DELETE_PHONE';

export const HOLD_EDIT_USER_TYPE = 'HOLD_EDIT_USER_TYPE';
export const HOLD_EDIT_USER = 'HOLD_EDIT_USER';
export const HOLD_EDIT_COURSE = 'HOLD_EDIT_COURSE';
export const HOLD_ADD_STUDENT = 'HOLD_ADD_STUDENT';
export const HOLD_REMOVE_STUDENT = 'HOLD_REMOVE_STUDENT';
export const HOLD_REMOVE_ASSIGNMENT = 'HOLD_REMOVE_ASSIGNMENT';
export const HOLD_EDIT_ASSIGNMENT = 'HOLD_EDIT_ASSIGNMENT';
export const HOLD_UPDATE_ASSIGNMENT = 'HOLD_UPDATE_ASSIGNMENT';
export const UPDATE_GRID = 'UPDATE_GRID';
export const HOLD_UPDATE_ASSIGNMENT_SCORE = 'HOLD_UPDATE_ASSIGNMENT_SCORE';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const GET_ALL_PARENTS = 'GET_ALL_PARENTS';
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_ALL_ADMIN = 'GET_ALL_ADMIN';

export const REMOVE_TEACHER = 'REMOVE_TEACHER';
export const ADD_TEACHER = 'ADD_TEACHER';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';

export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';

export const REMOVE_PARENT = 'REMOVE_PARENT';
export const ADD_PARENT = 'ADD_PARENT';
export const UPDATE_PARENT = 'UPDATE_PARENT';

export const REMOVE_ADMIN = 'REMOVE_ADMIN';
export const ADD_ADMIN = 'ADD_ADMIN';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';

export const ADD_USER_TO_LIST = "ADD_USER_TO_LIST";
export const REMOVE_USER_FROM_LIST = "REMOVE_USER_FROM_LIST";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const REMOVE_USER_MESSAGE = 'REMOVE_USER_MESSAGE';

export const ADD_CALENDAR_ITEM = 'ADD_CALENDAR_ITEM';
export const REMOVE_CALENDAR_ITEM = 'REMOVE_CALENDAR_ITEM';
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';